version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    environment:
      MONGO_INITDB_DATABASE: clean-node-api
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"